[build]
builder = "NIXPACKS"
buildCommand = "npm install --frozen-lockfile && npm run build"
startCommand = "npm run start:prod"

[deploy]
healthcheckPath = "/auth/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

